"""dometic-ddmp: local Wi-Fi client for Dometic CFX5 coolers (DDMP v2 / DDM2)."""

from .aio import AsyncClient
from .discovery import (
    DdmdReply,
    Discovered,
    MdnsService,
    async_discover,
    async_find_cooler,
    discover,
    find_cooler,
    probe_ddmd,
    query_mdns,
)
from .errors import (
    ConnectionClosed,
    DdmpError,
    DecodeError,
    NotWritable,
    StateUnknown,
    WriteRejected,
    WriteTimeout,
)
from .models import (
    ERROR_TEXT,
    BatteryProtection,
    Compartment,
    CoolerState,
    PowerSource,
    ProductType,
    error_text,
)
from .protocol import (
    DEFAULT_PORT,
    NEVER_WRITE,
    SUBSCRIBE_TOPICS,
    TOPIC_BY_ADDRESS,
    TOPIC_BY_NAME,
    TOPICS,
    WRITABLE,
    Action,
    Address,
    Frame,
    LineDecoder,
    Topic,
    assert_writable,
    publish_frame,
    subscribe_frame,
    topic,
)
from .session import Event, Nak, Publish, Session, Unhandled, WriteExpectation
from .sync_client import SyncClient

__version__ = "0.1.2"

__all__ = [
    "DEFAULT_PORT",
    "ERROR_TEXT",
    "NEVER_WRITE",
    "SUBSCRIBE_TOPICS",
    "TOPICS",
    "TOPIC_BY_ADDRESS",
    "TOPIC_BY_NAME",
    "WRITABLE",
    "Action",
    "Address",
    "AsyncClient",
    "BatteryProtection",
    "Compartment",
    "ConnectionClosed",
    "CoolerState",
    "DdmdReply",
    "DdmpError",
    "DecodeError",
    "Discovered",
    "Event",
    "Frame",
    "LineDecoder",
    "MdnsService",
    "Nak",
    "NotWritable",
    "PowerSource",
    "ProductType",
    "Publish",
    "Session",
    "StateUnknown",
    "SyncClient",
    "Topic",
    "Unhandled",
    "WriteExpectation",
    "WriteRejected",
    "WriteTimeout",
    "__version__",
    "assert_writable",
    "async_discover",
    "async_find_cooler",
    "discover",
    "error_text",
    "find_cooler",
    "probe_ddmd",
    "publish_frame",
    "query_mdns",
    "subscribe_frame",
    "topic",
]
